// examples/crypto-svelte/frontend/src/App.svelte
<script>
  // window.Zigware.invoke is injected by the Zigware runtime. The "cryptoDemo"
  // command is defined in src/commands/crypto.zig.
  let password = $state("correct horse battery staple");
  let message = $state("attack at dawn");
  let result = $state(null);
  let error = $state("");
  let busy = $state(false);

  async function run() {
    error = "";
    result = null;
    busy = true;
    try {
      result = await window.Zigware.invoke("cryptoDemo", { password, message });
    } catch (err) {
      error = err?.message ?? String(err);
    } finally {
      busy = false;
    }
  }
</script>

<main class="app">
  <h1>Crypto round-trip</h1>
  <p class="hint">
    Zig hashes the password with SHA-256, then encrypts the message with
    ChaCha20-Poly1305 and decrypts it back to prove the round-trip.
  </p>

  <form class="form" onsubmit={(e) => { e.preventDefault(); run(); }}>
    <label class="label" for="password">Password</label>
    <input id="password" class="field" type="password" autocomplete="off" bind:value={password} />
    <label class="label" for="message">Message to encrypt</label>
    <input id="message" class="field" type="text" bind:value={message} />
    <button class="btn" type="submit" disabled={busy}>
      {busy ? "Working…" : "Hash & encrypt"}
    </button>
  </form>

  {#if result}
    <pre class="out">SHA-256(password): {result.sha256}
nonce:             {result.nonce}
ciphertext:        {result.ciphertext}
tag:               {result.tag}
decrypted:         {result.decrypted}
round-trip:        {result.roundTrip ? "ok ✓" : "FAILED ✗"}</pre>
  {/if}
  {#if error}
    <p class="err">error: {error}</p>
  {/if}
</main>

// examples/crypto-react/frontend/App.jsx
import { useState } from "react";

// Calls the Zig `cryptoDemo` command over the bridge. `window.Zigware` is
// injected by the Zigware runtime; run `zig build dts` to type `invoke` from
// src/commands. cryptoDemo({ password, message }) resolves with
// { sha256, nonce, ciphertext, tag, decrypted, roundTrip } (byte fields hex).
export default function App() {
  const [password, setPassword] = useState("correct horse battery staple");
  const [message, setMessage] = useState("attack at dawn");
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  async function onSubmit(e) {
    e.preventDefault();
    setError("");
    setResult(null);
    setBusy(true);
    try {
      const r = await window.Zigware.invoke("cryptoDemo", { password, message });
      setResult(r);
    } catch (err) {
      setError(String(err && err.message ? err.message : err));
    } finally {
      setBusy(false);
    }
  }

  return (
    <main className="app">
      <h1>Crypto round-trip</h1>
      <p className="hint">
        Zig hashes the password with SHA-256, then encrypts the message with
        ChaCha20-Poly1305 and decrypts it back to prove the round-trip.
      </p>
      <form className="form" onSubmit={onSubmit}>
        <label className="label" htmlFor="password">
          Password
        </label>
        <input
          id="password"
          className="field"
          type="password"
          autoComplete="off"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <label className="label" htmlFor="message">
          Message to encrypt
        </label>
        <input
          id="message"
          className="field"
          type="text"
          value={message}
          onChange={(e) => setMessage(e.target.value)}
        />
        <button className="btn" type="submit" disabled={busy}>
          {busy ? "Working…" : "Hash & encrypt"}
        </button>
      </form>
      {result ? (
        <pre className="out">
          {`SHA-256(password): ${result.sha256}
nonce:             ${result.nonce}
ciphertext:        ${result.ciphertext}
tag:               ${result.tag}
decrypted:         ${result.decrypted}
round-trip:        ${result.roundTrip ? "ok ✓" : "FAILED ✗"}`}
        </pre>
      ) : null}
      {error ? <p className="err">error: {error}</p> : null}
    </main>
  );
}
